package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// RequestAccess is the resolver for the requestAccess field.
func (r *mutationResolver) RequestAccess(ctx context.Context, reason *string) (*model.User, error) {
	reasonText := ""
	if reason != nil {
		reasonText = *reason
	}
	if err := r.app.RequestAccess(ctx, reasonText); err != nil {
		return nil, err
	}
	return r.Query().Me(ctx)
}

// ApproveUser is the resolver for the approveUser field.
func (r *mutationResolver) ApproveUser(ctx context.Context, email string) (*model.AccessEntry, error) {
	return toGraphAccessEntry(r.app.ApproveUser(ctx, email))
}

// RejectUser is the resolver for the rejectUser field.
func (r *mutationResolver) RejectUser(ctx context.Context, email string) (*model.AccessEntry, error) {
	return toGraphAccessEntry(r.app.RejectUser(ctx, email))
}

// RevokeUser is the resolver for the revokeUser field.
func (r *mutationResolver) RevokeUser(ctx context.Context, email string) (*model.AccessEntry, error) {
	return toGraphAccessEntry(r.app.RevokeUser(ctx, email))
}

// ResetUser is the resolver for the resetUser field.
func (r *mutationResolver) ResetUser(ctx context.Context, email string) (bool, error) {
	return r.app.ResetUser(ctx, email)
}

// AccessEntries is the resolver for the accessEntries field.
func (r *queryResolver) AccessEntries(ctx context.Context) ([]*model.AccessEntry, error) {
	rows, err := r.app.UserAccessList(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AccessEntry, 0, len(rows))
	for _, row := range rows {
		out = append(out, toGraphAccess(row))
	}
	return out, nil
}

// Access is the resolver for the access field.
func (r *userResolver) Access(ctx context.Context, obj *model.User) (model.AccessStatus, error) {
	status, err := r.app.AccessStatus(ctx, obj.Email)
	if err != nil {
		return "", err
	}
	return toGraphAccessStatus(status), nil
}
