package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// AssignmentActivity is the resolver for the assignmentActivity field.
func (r *queryResolver) AssignmentActivity(ctx context.Context, course string, name string) ([]*model.ActivityEntry, error) {
	entries, err := r.app.AssignmentActivity(ctx, course, name)
	if err != nil {
		return nil, err
	}
	return toGraphActivity(entries), nil
}

// CourseActivity is the resolver for the courseActivity field.
func (r *queryResolver) CourseActivity(ctx context.Context, course string) ([]*model.ActivityEntry, error) {
	entries, err := r.app.CourseActivity(ctx, course)
	if err != nil {
		return nil, err
	}
	return toGraphActivity(entries), nil
}

// ActivityLog is the resolver for the activityLog field.
func (r *queryResolver) ActivityLog(ctx context.Context) ([]*model.ActivityEntry, error) {
	entries, err := r.app.ActivityLog(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphActivity(entries), nil
}
