package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// SendSummaryNow is the resolver for the sendSummaryNow field.
func (r *mutationResolver) SendSummaryNow(ctx context.Context) (bool, error) {
	if err := r.app.SendSummaryNow(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// PlatformEvents is the resolver for the platformEvents field.
func (r *queryResolver) PlatformEvents(ctx context.Context, since *time.Time) ([]*model.Event, error) {
	start := time.Now().Add(-48 * time.Hour)
	if since != nil {
		start = *since
	}
	events, err := r.app.PlatformEvents(ctx, start)
	if err != nil {
		return nil, err
	}
	return toGraphEvents(events), nil
}

// PlatformSummary is the resolver for the platformSummary field.
func (r *queryResolver) PlatformSummary(ctx context.Context, since *time.Time, until *time.Time) (*model.PlatformSummary, error) {
	now := time.Now()
	start, end := now.Add(-24*time.Hour), now
	if since != nil {
		start = *since
	}
	if until != nil {
		end = *until
	}
	summary, err := r.app.PlatformSummary(ctx, start, end)
	if err != nil {
		return nil, err
	}
	return toGraphSummary(summary), nil
}
