package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/obcode/glabs/v3/web/app"
	"github.com/obcode/glabs/v3/web/db"
	"github.com/obcode/glabs/v3/web/graph/model"
)

// SetAssignment is the resolver for the setAssignment field.
func (r *mutationResolver) SetAssignment(ctx context.Context, course string, name string, draft []*model.FieldValueInput) (*model.AssignmentView, error) {
	view, err := r.app.SetAssignment(ctx, course, name, draftToMap(draft))
	if err != nil {
		return nil, err
	}
	return toGraphAssignmentView(view), nil
}

// ImportAssignmentYaml is the resolver for the importAssignmentYAML field.
func (r *mutationResolver) ImportAssignmentYaml(ctx context.Context, course string, yaml string) (*model.AssignmentView, error) {
	view, err := r.app.ImportAssignmentYAML(ctx, course, yaml)
	if err != nil {
		return nil, err
	}
	return toGraphAssignmentView(view), nil
}

// DeleteAssignment is the resolver for the deleteAssignment field.
func (r *mutationResolver) DeleteAssignment(ctx context.Context, course string, name string) (bool, error) {
	return r.app.DeleteAssignment(ctx, course, name)
}

// AssignmentSchema is the resolver for the assignmentSchema field.
func (r *queryResolver) AssignmentSchema(ctx context.Context) ([]*model.FieldMeta, error) {
	return toGraphAssignmentSchema(app.AssignmentSchema()), nil
}

// BranchRuleSchema is the resolver for the branchRuleSchema field.
func (r *queryResolver) BranchRuleSchema(ctx context.Context) ([]*model.FieldMeta, error) {
	return toGraphAssignmentSchema(app.AssignmentBranchSchema()), nil
}

// ApprovalSettingsSchema is the resolver for the approvalSettingsSchema field.
func (r *queryResolver) ApprovalSettingsSchema(ctx context.Context) ([]*model.FieldMeta, error) {
	return toGraphAssignmentSchema(app.AssignmentApprovalSettingsSchema()), nil
}

// ApprovalRuleSchema is the resolver for the approvalRuleSchema field.
func (r *queryResolver) ApprovalRuleSchema(ctx context.Context) ([]*model.FieldMeta, error) {
	return toGraphAssignmentSchema(app.AssignmentApprovalRuleSchema()), nil
}

// Assignment is the resolver for the assignment field.
func (r *queryResolver) Assignment(ctx context.Context, course string, name string) (*model.AssignmentView, error) {
	view, err := r.app.Assignment(ctx, course, name)
	if err != nil {
		if errors.Is(err, db.ErrCourseNotFound) {
			return nil, nil
		}
		return nil, err
	}
	if view == nil {
		return nil, nil
	}
	return toGraphAssignmentView(view), nil
}

// ValidateAssignmentDraft is the resolver for the validateAssignmentDraft field.
func (r *queryResolver) ValidateAssignmentDraft(ctx context.Context, course string, name string, draft []*model.FieldValueInput) (*model.ValidationResult, error) {
	vr, err := r.app.ValidateAssignmentDraft(ctx, course, name, draftToMap(draft))
	if err != nil {
		return nil, err
	}
	return toGraphValidationResult(vr), nil
}

// AssignmentUrls is the resolver for the assignmentUrls field.
func (r *queryResolver) AssignmentUrls(ctx context.Context, course string, name string) (*model.AssignmentUrls, error) {
	u, err := r.app.AssignmentURLs(ctx, course, name)
	if err != nil {
		if errors.Is(err, db.ErrCourseNotFound) {
			return nil, nil
		}
		return nil, err
	}
	if u == nil {
		return nil, nil
	}
	return toGraphAssignmentURLs(u), nil
}
