package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/obcode/glabs/v3/web/app"
	"github.com/obcode/glabs/v3/web/db"
	"github.com/obcode/glabs/v3/web/graph/model"
)

// AssignmentSchema is the resolver for the assignmentSchema field.
func (r *queryResolver) AssignmentSchema(ctx context.Context) ([]*model.FieldMeta, error) {
	return toGraphAssignmentSchema(app.AssignmentSchema()), nil
}

// Assignment is the resolver for the assignment field.
func (r *queryResolver) Assignment(ctx context.Context, course string, name string) (*model.AssignmentView, error) {
	view, err := r.app.Assignment(ctx, course, name)
	if err != nil {
		if errors.Is(err, db.ErrCourseNotFound) {
			return nil, nil
		}
		return nil, err
	}
	if view == nil {
		return nil, nil
	}
	return toGraphAssignmentView(view), nil
}
