package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/obcode/glabs/v3/web/app"
	"github.com/obcode/glabs/v3/web/db"
	"github.com/obcode/glabs/v3/web/graph/model"
)

// AssignmentSchema is the resolver for the assignmentSchema field.
func (r *queryResolver) AssignmentSchema(ctx context.Context) ([]*model.FieldMeta, error) {
	fields := app.AssignmentSchema()
	out := make([]*model.FieldMeta, 0, len(fields))
	for _, f := range fields {
		opts := make([]*model.FieldOption, 0, len(f.Options))
		for _, o := range f.Options {
			opts = append(opts, &model.FieldOption{Value: o.Value, Label: o.Label, Description: o.Description})
		}
		out = append(out, &model.FieldMeta{
			Key:         f.Key,
			Label:       f.Label,
			Description: f.Description,
			Kind:        model.FieldKind(f.Kind),
			Required:    f.Required,
			Deprecated:  f.Deprecated,
			Example:     emptyToNil(f.Example),
			Options:     opts,
		})
	}
	return out, nil
}

// Assignment is the resolver for the assignment field.
func (r *queryResolver) Assignment(ctx context.Context, course string, name string) (*model.AssignmentView, error) {
	view, err := r.app.Assignment(ctx, course, name)
	if err != nil {
		if errors.Is(err, db.ErrCourseNotFound) {
			return nil, nil
		}
		return nil, err
	}
	if view == nil {
		return nil, nil
	}
	return &model.AssignmentView{
		Course:       view.Course,
		Name:         view.Name,
		Extends:      emptyToNil(view.Extends),
		Abstract:     view.Abstract,
		Resolved:     view.Resolved,
		ResolveError: emptyToNil(view.ResolveError),
	}, nil
}

// emptyToNil maps an empty string to nil, for nullable GraphQL String fields.
func emptyToNil(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}
