package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/obcode/glabs/v3/web/db"
	"github.com/obcode/glabs/v3/web/graph/model"
)

// CourseCheck is the resolver for the courseCheck field.
func (r *queryResolver) CourseCheck(ctx context.Context, name string) (*model.CheckResult, error) {
	res, err := r.app.CheckCourse(ctx, name)
	if err != nil {
		if errors.Is(err, db.ErrCourseNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return toGraphCheckResult(res), nil
}

// CourseCheckProgress is the resolver for the courseCheckProgress field.
func (r *subscriptionResolver) CourseCheckProgress(ctx context.Context, name string) (<-chan *model.CheckProgress, error) {
	events, err := r.app.StreamCheckCourse(ctx, name)
	if err != nil {
		return nil, err
	}
	out := make(chan *model.CheckProgress)
	go func() {
		defer close(out)
		for ev := range events {
			p := &model.CheckProgress{Message: ev.Message, Done: ev.Done}
			if ev.Error != "" {
				msg := ev.Error
				p.Error = &msg
			}
			if ev.Result != nil {
				p.Result = toGraphCheckResult(ev.Result)
			}
			select {
			case out <- p:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}
