package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// SetGitlabToken is the resolver for the setGitlabToken field.
func (r *mutationResolver) SetGitlabToken(ctx context.Context, token string) (*model.GitLabTokenStatus, error) {
	status, err := r.app.SetGitLabToken(ctx, token)
	if err != nil {
		return nil, err
	}
	return toGraphTokenStatus(status), nil
}

// RemoveGitlabToken is the resolver for the removeGitlabToken field.
func (r *mutationResolver) RemoveGitlabToken(ctx context.Context) (*model.GitLabTokenStatus, error) {
	status, err := r.app.RemoveGitLabToken(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphTokenStatus(status), nil
}

// GitlabToken is the resolver for the gitlabToken field.
func (r *queryResolver) GitlabToken(ctx context.Context) (*model.GitLabTokenStatus, error) {
	status, err := r.app.GitLabTokenStatus(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphTokenStatus(status), nil
}
