package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// PlanOp is the resolver for the planOp field.
func (r *mutationResolver) PlanOp(ctx context.Context, op model.Op, course string, assignment string, params *model.OpParams, onlyFor []string) (*model.OpPlan, error) {
	plan, err := r.app.PlanOp(ctx, opToString(op), course, assignment, paramsToMap(params), onlyFor)
	if err != nil {
		return nil, err
	}
	return toGraphOpPlan(plan), nil
}
