package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/obcode/glabs/v3/web/db"
	"github.com/obcode/glabs/v3/web/graph/model"
)

// AssignmentReport is the resolver for the assignmentReport field.
func (r *queryResolver) AssignmentReport(ctx context.Context, course string, name string) (*model.AssignmentReport, error) {
	rep, err := r.app.AssignmentReport(ctx, course, name)
	if err != nil {
		if errors.Is(err, db.ErrCourseNotFound) {
			return nil, nil
		}
		return nil, err
	}
	if rep == nil {
		return nil, nil
	}
	return toGraphAssignmentReport(rep), nil
}
