package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// CourseRepoOverview is the resolver for the courseRepoOverview field.
func (r *queryResolver) CourseRepoOverview(ctx context.Context, course string) ([]*model.AssignmentRepos, error) {
	overview, err := r.app.CourseRepoOverview(ctx, course)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AssignmentRepos, 0, len(overview))
	for _, a := range overview {
		repos := make([]*model.RepoStatus, 0, len(a.Repos))
		for _, r := range a.Repos {
			repos = append(repos, &model.RepoStatus{For: r.For, Repo: r.Repo, URL: r.URL, Exists: r.Exists})
		}
		out = append(out, &model.AssignmentRepos{
			Name:     a.Name,
			Per:      a.Per,
			Targets:  a.Targets,
			Existing: a.Existing,
			Repos:    repos,
			Note:     emptyToNil(a.Note),
		})
	}
	return out, nil
}
