package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// CourseRepoOverview is the resolver for the courseRepoOverview field.
func (r *queryResolver) CourseRepoOverview(ctx context.Context, course string) ([]*model.AssignmentRepos, error) {
	overview, err := r.app.CourseRepoOverview(ctx, course)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AssignmentRepos, 0, len(overview))
	for _, a := range overview {
		out = append(out, toGraphAssignmentRepos(a))
	}
	return out, nil
}

// CourseRepoOverviewProgress is the resolver for the courseRepoOverviewProgress field.
func (r *subscriptionResolver) CourseRepoOverviewProgress(ctx context.Context, course string) (<-chan *model.RepoOverviewEvent, error) {
	events, err := r.app.StreamCourseRepoOverview(ctx, course)
	if err != nil {
		return nil, err
	}
	out := make(chan *model.RepoOverviewEvent)
	go func() {
		defer close(out)
		for ev := range events {
			p := &model.RepoOverviewEvent{Total: ev.Total, Done: ev.Done}
			if ev.Assignment != nil {
				p.Assignment = toGraphAssignmentRepos(ev.Assignment)
			}
			if ev.Error != "" {
				msg := ev.Error
				p.Error = &msg
			}
			select {
			case out <- p:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}
