package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// ScheduleOp is the resolver for the scheduleOp field.
func (r *mutationResolver) ScheduleOp(ctx context.Context, token string, runAt time.Time, graceMinutes *int, confirmPhrase *string) (*model.ScheduledJob, error) {
	phrase := ""
	if confirmPhrase != nil {
		phrase = *confirmPhrase
	}
	job, err := r.app.ScheduleOp(ctx, token, runAt, graceMinutes, phrase)
	if err != nil {
		return nil, err
	}
	return toGraphJob(job), nil
}

// CancelScheduledJob is the resolver for the cancelScheduledJob field.
func (r *mutationResolver) CancelScheduledJob(ctx context.Context, id string) (*model.ScheduledJob, error) {
	job, err := r.app.CancelScheduledJob(ctx, id)
	if err != nil {
		return nil, err
	}
	return toGraphJob(job), nil
}

// ScheduledJobs is the resolver for the scheduledJobs field.
func (r *queryResolver) ScheduledJobs(ctx context.Context, status []model.JobStatus) ([]*model.ScheduledJob, error) {
	jobs, err := r.app.ScheduledJobs(ctx, toDBStatuses(status))
	if err != nil {
		return nil, err
	}
	return toGraphJobs(jobs), nil
}

// ScheduledJob is the resolver for the scheduledJob field.
func (r *queryResolver) ScheduledJob(ctx context.Context, id string) (*model.ScheduledJob, error) {
	job, err := r.app.ScheduledJob(ctx, id)
	if err != nil {
		return nil, err
	}
	return toGraphJob(job), nil
}
