package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/glabs/v3/web/graph/model"
)

// CourseStudents is the resolver for the courseStudents field.
func (r *queryResolver) CourseStudents(ctx context.Context, course string) ([]*model.CourseStudent, error) {
	students, err := r.app.CourseStudents(ctx, course)
	if err != nil {
		return nil, err
	}
	out := make([]*model.CourseStudent, 0, len(students))
	for _, s := range students {
		out = append(out, &model.CourseStudent{
			Email:     s.Email,
			Found:     s.Found,
			FirstName: emptyToNil(s.FirstName),
			LastName:  emptyToNil(s.LastName),
			Gender:    emptyToNil(s.Gender),
			Group:     emptyToNil(s.Group),
			Mtknr:     emptyToNil(s.Mtknr),
		})
	}
	return out, nil
}
