// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

// Version and build metadata for the running server.
type ServerInfo struct {
	Version string `json:"version"`
	Commit  string `json:"commit"`
	Date    string `json:"date"`
}
