// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// One assignment in source (own) form plus its resolved preview — the same
// rendering `glabs show` produces, so inheritance is visible.
type AssignmentView struct {
	Course string `json:"course"`
	Name   string `json:"name"`
	// The assignment this one inherits from, if any (`extends`).
	Extends *string `json:"extends,omitempty"`
	// Whether this is an abstract base (a template for `extends`).
	Abstract bool `json:"abstract"`
	// The assignment's own (source) field values, keyed by FieldMeta.key, for pre-filling the editor form.
	Own []*FieldValue `json:"own"`
	// The resolved config rendered as text (may contain ANSI); empty when resolveError is set.
	Resolved string `json:"resolved"`
	// Why the assignment could not be resolved (e.g. abstract base, missing parent) — not an error.
	ResolveError *string `json:"resolveError,omitempty"`
}

// A course as stored for the current user. Each user sees only their own courses;
// there is no way to reach another user's course.
type Course struct {
	Name         string `json:"name"`
	CoursePath   string `json:"coursePath"`
	SemesterPath string `json:"semesterPath"`
	// The names of the assignments in this course, sorted.
	AssignmentNames []string  `json:"assignmentNames"`
	StudentCount    int       `json:"studentCount"`
	GroupCount      int       `json:"groupCount"`
	ImportedAt      time.Time `json:"importedAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// The assignment editor is schema-driven: the GUI renders a guided, validated form
// from this server-authoritative metadata, so labels, help text and dropdown
// options live in exactly one place.
type FieldMeta struct {
	// Config key, e.g. `per` or `accesslevel`.
	Key string `json:"key"`
	// Human-readable label for the form.
	Label string `json:"label"`
	// Short help text describing what the field does.
	Description string `json:"description"`
	// The input shape the GUI should render.
	Kind FieldKind `json:"kind"`
	// Whether the field must be set for a concrete (non-abstract) assignment.
	Required bool `json:"required"`
	// Whether the field is deprecated (shown but discouraged).
	Deprecated bool `json:"deprecated"`
	// An example value for the input placeholder, if any.
	Example *string `json:"example,omitempty"`
	// Dropdown options for an ENUM field (empty otherwise).
	Options []*FieldOption `json:"options"`
}

// One choice of an ENUM field — a dropdown entry with its own short description.
type FieldOption struct {
	Value       string `json:"value"`
	Label       string `json:"label"`
	Description string `json:"description"`
}

// One field's own (source) value for an assignment — what the user wrote, before
// inheritance. Values are stringified (booleans as `true`/`false`) and keyed by the
// same `key` as FieldMeta, so the GUI can pre-fill each schema field generically.
type FieldValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// One field's drafted value, keyed by FieldMeta.key. Booleans as `true`/`false`; empty string unsets the field (so it inherits).
type FieldValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// One lint finding: configuration that does not do what it looks like it does.
type Finding struct {
	Path     string          `json:"path"`
	Message  string          `json:"message"`
	Severity FindingSeverity `json:"severity"`
}

// Whether the current user has stored a GitLab token, and when it was last set.
// The token itself is never returned by any query.
type GitLabTokenStatus struct {
	Set       bool       `json:"set"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// Version and build metadata for the running server.
type ServerInfo struct {
	Version string `json:"version"`
	Commit  string `json:"commit"`
	Date    string `json:"date"`
}

// Result of validating a draft assignment against the real resolver (the same one
// the CLI uses), without saving.
type ValidationResult struct {
	// Whether the draft is structurally sound and could be saved.
	Ok bool `json:"ok"`
	// Hard errors that make the draft unsaveable (empty when ok).
	Errors []string `json:"errors"`
	// The resolved config preview (Show() output, may contain ANSI) when the draft resolves.
	Resolved *string `json:"resolved,omitempty"`
	// Why there is no preview though the draft is ok — e.g. an abstract base.
	ResolveError *string `json:"resolveError,omitempty"`
}

// The input shape the GUI should render for a field.
type FieldKind string

const (
	FieldKindString     FieldKind = "STRING"
	FieldKindBool       FieldKind = "BOOL"
	FieldKindEnum       FieldKind = "ENUM"
	FieldKindInt        FieldKind = "INT"
	FieldKindStringlist FieldKind = "STRINGLIST"
)

var AllFieldKind = []FieldKind{
	FieldKindString,
	FieldKindBool,
	FieldKindEnum,
	FieldKindInt,
	FieldKindStringlist,
}

func (e FieldKind) IsValid() bool {
	switch e {
	case FieldKindString, FieldKindBool, FieldKindEnum, FieldKindInt, FieldKindStringlist:
		return true
	}
	return false
}

func (e FieldKind) String() string {
	return string(e)
}

func (e *FieldKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FieldKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FieldKind", str)
	}
	return nil
}

func (e FieldKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FieldKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FieldKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FindingSeverity string

const (
	// The setting is present but has no effect.
	FindingSeverityProblem FindingSeverity = "PROBLEM"
	// It works, but the spelling or shape is obsolete.
	FindingSeverityDeprecated FindingSeverity = "DEPRECATED"
)

var AllFindingSeverity = []FindingSeverity{
	FindingSeverityProblem,
	FindingSeverityDeprecated,
}

func (e FindingSeverity) IsValid() bool {
	switch e {
	case FindingSeverityProblem, FindingSeverityDeprecated:
		return true
	}
	return false
}

func (e FindingSeverity) String() string {
	return string(e)
}

func (e *FindingSeverity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FindingSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FindingSeverity", str)
	}
	return nil
}

func (e FindingSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FindingSeverity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FindingSeverity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
