package config

import (
	"testing"

	"github.com/spf13/viper"
)

func TestAssignmentPath(t *testing.T) {
	resetViper(t)
	viper.Set("course.coursepath", "mpd")
	viper.Set("course.semesterpath", "ss26")
	viper.Set("course.a1.assignmentpath", "blatt-01")

	got := assignmentPath("course", "a1")
	want := "mpd/ss26/blatt-01"

	if got != want {
		t.Fatalf("assignmentPath() = %q, want %q", got, want)
	}
}

func TestPerAndDescriptionDefaults(t *testing.T) {
	resetViper(t)

	if got := per("course.a1"); got != PerStudent {
		t.Fatalf("per() default = %q, want %q", got, PerStudent)
	}

	viper.Set("course.a1.per", "group")
	if got := per("course.a1"); got != PerGroup {
		t.Fatalf("per() for group = %q, want %q", got, PerGroup)
	}

	if got := description("course.a1"); got != "generated by glabs" {
		t.Fatalf("description() default = %q", got)
	}

	viper.Set("course.a1.description", "custom")
	if got := description("course.a1"); got != "custom" {
		t.Fatalf("description() override = %q", got)
	}
}

func TestRepoNamingHelpers(t *testing.T) {
	id := 123
	mail := "a@b.example"
	user := "alice"

	cfg := &AssignmentConfig{Course: "mpd", Name: "blatt01", UseCoursenameAsPrefix: true}

	if got := cfg.RepoSuffix(&Student{Email: &mail}); got != "a_at_b.example" {
		t.Fatalf("RepoSuffix(email) = %q", got)
	}
	if got := cfg.RepoSuffix(&Student{Id: &id}); got != "123" {
		t.Fatalf("RepoSuffix(id) = %q", got)
	}
	if got := cfg.RepoSuffix(&Student{Username: &user}); got != "alice" {
		t.Fatalf("RepoSuffix(username) = %q", got)
	}
	if got := cfg.RepoSuffix(&Student{}); got != "" {
		t.Fatalf("RepoSuffix(empty) = %q", got)
	}

	if got := cfg.RepoBaseName(); got != "mpd-blatt01" {
		t.Fatalf("RepoBaseName() = %q", got)
	}
	if got := cfg.RepoNameWithSuffix("g1"); got != "mpd-blatt01-g1" {
		t.Fatalf("RepoNameWithSuffix() = %q", got)
	}
	if got := cfg.RepoNameForStudent(&Student{Username: &user}); got != "mpd-blatt01-alice" {
		t.Fatalf("RepoNameForStudent() = %q", got)
	}
	if got := cfg.RepoNameForGroup(&Group{Name: "team1"}); got != "mpd-blatt01-team1" {
		t.Fatalf("RepoNameForGroup() = %q", got)
	}

	cfg.UseCoursenameAsPrefix = false
	if got := cfg.RepoBaseName(); got != "blatt01" {
		t.Fatalf("RepoBaseName() without course prefix = %q", got)
	}
}

func TestGetAssignmentConfig(t *testing.T) {
	resetViper(t)

	viper.Set("gitlab.host", "https://gitlab.example.org")
	viper.Set("course", true)
	viper.Set("course.coursepath", "mpd")
	viper.Set("course.semesterpath", "ss26")
	viper.Set("course.useCoursenameAsPrefix", true)
	viper.Set("course.students", []string{"alice", "1001"})
	viper.Set("course.a1", true)
	viper.Set("course.a1.assignmentpath", "blatt-01")
	viper.Set("course.a1.per", "student")
	viper.Set("course.a1.description", "blatt 1")
	viper.Set("course.a1.mergeRequest", map[string]any{"mergeMethod": "semi_linear"})
	viper.Set("course.a1.mergeRequest.mergeMethod", "semi_linear")
	viper.Set("course.a1.release", map[string]any{"dockerImages": []string{"registry/app"}})
	viper.Set("course.a1.release.dockerImages", []string{"registry/app"})

	cfg := GetAssignmentConfig("course", "a1")

	if cfg.Path != "mpd/ss26/blatt-01" {
		t.Fatalf("Path = %q", cfg.Path)
	}
	if cfg.URL != "https://gitlab.example.org/mpd/ss26/blatt-01" {
		t.Fatalf("URL = %q", cfg.URL)
	}
	if cfg.Per != PerStudent {
		t.Fatalf("Per = %q", cfg.Per)
	}
	if !cfg.ContainerRegistry {
		t.Fatal("ContainerRegistry should be true when release docker images are configured")
	}
	if cfg.Release == nil || len(cfg.Release.DockerImages) != 1 {
		t.Fatalf("Release DockerImages = %#v", cfg.Release)
	}
	if cfg.Clone == nil {
		t.Fatal("Clone should be initialized with defaults")
	}
	if len(cfg.Students) != 2 {
		t.Fatalf("Students len = %d, want 2", len(cfg.Students))
	}
	if cfg.AccessLevel != Developer {
		t.Fatalf("AccessLevel = %v, want %v", cfg.AccessLevel, Developer)
	}
	if cfg.MergeRequest == nil || cfg.MergeRequest.MergeMethod != SemiLinearHistory {
		t.Fatalf("MergeRequest = %#v, want semi_linear", cfg.MergeRequest)
	}
}

func TestGetAssignmentConfig_DefaultMergeRequest(t *testing.T) {
	resetViper(t)

	viper.Set("gitlab.host", "https://gitlab.example.org")
	viper.Set("course", true)
	viper.Set("course.coursepath", "mpd")
	viper.Set("course.a1", true)
	viper.Set("course.a1.assignmentpath", "blatt-01")

	cfg := GetAssignmentConfig("course", "a1")

	if cfg.MergeRequest == nil {
		t.Fatal("MergeRequest should be initialized with defaults")
	}
	if cfg.MergeRequest.MergeMethod != MergeCommit {
		t.Fatalf("MergeRequest.MergeMethod = %q, want %q", cfg.MergeRequest.MergeMethod, MergeCommit)
	}
	if cfg.MergeRequest.SquashOption != SquashDefaultOff {
		t.Fatalf("MergeRequest.SquashOption = %q, want %q", cfg.MergeRequest.SquashOption, SquashDefaultOff)
	}
}

func TestGetAssignmentConfig_SquashOption(t *testing.T) {
	cases := []struct {
		value string
		want  SquashOption
	}{
		{"never", SquashNever},
		{"always", SquashAlways},
		{"default_on", SquashDefaultOn},
		{"default_off", SquashDefaultOff},
	}
	for _, tc := range cases {
		t.Run(tc.value, func(t *testing.T) {
			resetViper(t)
			viper.Set("gitlab.host", "https://gitlab.example.org")
			viper.Set("course", true)
			viper.Set("course.coursepath", "mpd")
			viper.Set("course.a1", true)
			viper.Set("course.a1.assignmentpath", "blatt-01")
			viper.Set("course.a1.mergeRequest.squashOption", tc.value)

			cfg := GetAssignmentConfig("course", "a1")

			if cfg.MergeRequest == nil {
				t.Fatal("MergeRequest should not be nil")
			}
			if cfg.MergeRequest.SquashOption != tc.want {
				t.Fatalf("SquashOption = %q, want %q", cfg.MergeRequest.SquashOption, tc.want)
			}
		})
	}
}
