package config

import "testing"

func TestAssignmentPath(t *testing.T) {
	registerCourse(t, `
course:
  coursepath: mpd
  semesterpath: ss26
  a1:
    assignmentpath: blatt-01
`)
	cfg := mustAssignmentConfig(t, "course", "a1")

	if want := "mpd/ss26/blatt-01"; cfg.Path != want {
		t.Fatalf("Path = %q, want %q", cfg.Path, want)
	}
	if want := goldenHost + "/mpd/ss26/blatt-01"; cfg.URL != want {
		t.Fatalf("URL = %q, want %q", cfg.URL, want)
	}
}

func TestPerAndDescriptionDefaults(t *testing.T) {
	registerCourse(t, `
course:
  a1:
    assignmentpath: blatt-01
  a2:
    assignmentpath: blatt-02
    per: group
    description: custom
`)

	bare := mustAssignmentConfig(t, "course", "a1")
	if bare.Per != PerStudent {
		t.Errorf("Per default = %q, want %q", bare.Per, PerStudent)
	}
	if want := "generated by glabs"; bare.Description != want {
		t.Errorf("Description default = %q, want %q", bare.Description, want)
	}

	set := mustAssignmentConfig(t, "course", "a2")
	if set.Per != PerGroup {
		t.Errorf("Per = %q, want %q", set.Per, PerGroup)
	}
	if set.Description != "custom" {
		t.Errorf("Description = %q, want %q", set.Description, "custom")
	}
}

// UseEmailDomainAsSuffix now means what it says: false selects the local part.
//
// It used to take a second reading of viper to decide, so that a zero-valued
// struct meant "use the domain" — the field being false was not enough, viper
// also had to say the key was unset. That crutch is gone with course files
// leaving viper, and resolution always sets the field (absent means true), so
// the only thing that changes is what a hand-built config means. Nothing but the
// resolver builds one.
func TestRepoSuffix(t *testing.T) {
	id := 123
	mail := "a@b.example"
	user := "alice"

	withDomain := &AssignmentConfig{Course: "mpd", Name: "blatt01", UseCoursenameAsPrefix: true, UseEmailDomainAsSuffix: true}
	if got := withDomain.RepoSuffix(&Student{Email: &mail}); got != "a_at_b.example" {
		t.Errorf("RepoSuffix(email) with domain = %q, want %q", got, "a_at_b.example")
	}

	localOnly := &AssignmentConfig{Course: "mpd", Name: "blatt01", UseCoursenameAsPrefix: true}
	if got := localOnly.RepoSuffix(&Student{Email: &mail}); got != "a" {
		t.Errorf("RepoSuffix(email) without domain = %q, want %q", got, "a")
	}

	for _, tt := range []struct {
		name    string
		student *Student
		want    string
	}{
		{"id", &Student{Id: &id}, "123"},
		{"username", &Student{Username: &user}, "alice"},
		{"empty", &Student{}, ""},
	} {
		if got := withDomain.RepoSuffix(tt.student); got != tt.want {
			t.Errorf("RepoSuffix(%s) = %q, want %q", tt.name, got, tt.want)
		}
	}
}

// The default resolves to true, so an assignment that says nothing keeps the
// domain in the repository name.
func TestUseEmailDomainAsSuffixDefaultsToTrue(t *testing.T) {
	registerCourse(t, `
course:
  students:
    - a@b.example
  a1:
    assignmentpath: blatt-01
`)
	cfg := mustAssignmentConfig(t, "course", "a1")

	if !cfg.UseEmailDomainAsSuffix {
		t.Fatal("UseEmailDomainAsSuffix = false, want true when the course says nothing")
	}
	if got := cfg.RepoSuffix(cfg.Students[0]); got != "a_at_b.example" {
		t.Errorf("RepoSuffix = %q, want %q", got, "a_at_b.example")
	}
}

func TestUseEmailDomainAsSuffixExplicitFalse(t *testing.T) {
	registerCourse(t, `
course:
  useEmailDomainAsSuffix: false
  students:
    - a@b.example
  a1:
    assignmentpath: blatt-01
`)
	cfg := mustAssignmentConfig(t, "course", "a1")

	if cfg.UseEmailDomainAsSuffix {
		t.Fatal("UseEmailDomainAsSuffix = true, want the explicit false to win")
	}
	if got := cfg.RepoSuffix(cfg.Students[0]); got != "a" {
		t.Errorf("RepoSuffix = %q, want %q", got, "a")
	}
}

func TestRepoNamingHelpers(t *testing.T) {
	user := "alice"
	cfg := &AssignmentConfig{Course: "mpd", Name: "blatt01", UseCoursenameAsPrefix: true, UseEmailDomainAsSuffix: true}

	if got := cfg.RepoBaseName(); got != "mpd-blatt01" {
		t.Errorf("RepoBaseName() = %q", got)
	}
	if got := cfg.RepoNameWithSuffix("g1"); got != "mpd-blatt01-g1" {
		t.Errorf("RepoNameWithSuffix() = %q", got)
	}
	if got := cfg.RepoNameForStudent(&Student{Username: &user}); got != "mpd-blatt01-alice" {
		t.Errorf("RepoNameForStudent() = %q", got)
	}
	if got := cfg.RepoNameForGroup(&Group{Name: "team1"}); got != "mpd-blatt01-team1" {
		t.Errorf("RepoNameForGroup() = %q", got)
	}

	noPrefix := &AssignmentConfig{Course: "mpd", Name: "blatt01"}
	if got := noPrefix.RepoBaseName(); got != "blatt01" {
		t.Errorf("RepoBaseName() without prefix = %q, want %q", got, "blatt01")
	}
}

func TestGetAssignmentConfig(t *testing.T) {
	registerCourse(t, `
course:
  coursepath: mpd
  semesterpath: ss26
  useCoursenameAsPrefix: true
  students:
    - alice
    - "1001"
  a1:
    assignmentpath: blatt-01
    per: student
    description: blatt 1
    mergeRequest:
      mergeMethod: semi_linear
    release:
      dockerImages:
        - registry/app
`)
	cfg := mustAssignmentConfig(t, "course", "a1")

	if want := "mpd/ss26/blatt-01"; cfg.Path != want {
		t.Errorf("Path = %q, want %q", cfg.Path, want)
	}
	if want := goldenHost + "/mpd/ss26/blatt-01"; cfg.URL != want {
		t.Errorf("URL = %q, want %q", cfg.URL, want)
	}
	if cfg.Per != PerStudent {
		t.Errorf("Per = %q, want %q", cfg.Per, PerStudent)
	}
	// Configuring docker images implies the registry, without saying so.
	if !cfg.ContainerRegistry {
		t.Error("ContainerRegistry = false, want true when release docker images are configured")
	}
	if cfg.Release == nil || len(cfg.Release.DockerImages) != 1 {
		t.Errorf("Release = %#v, want one docker image", cfg.Release)
	}
	if cfg.Clone == nil {
		t.Error("Clone = nil, want defaults")
	}
	if len(cfg.Students) != 2 {
		t.Errorf("Students = %d, want 2", len(cfg.Students))
	}
	if cfg.AccessLevel != Developer {
		t.Errorf("AccessLevel = %v, want %v", cfg.AccessLevel, Developer)
	}
	if cfg.MergeRequest == nil || cfg.MergeRequest.MergeMethod != SemiLinearHistory {
		t.Errorf("MergeRequest = %#v, want mergeMethod %q", cfg.MergeRequest, SemiLinearHistory)
	}
}

func TestMergeRequestDefaults(t *testing.T) {
	registerCourse(t, `
course:
  a1:
    assignmentpath: blatt-01
`)
	mr := mustAssignmentConfig(t, "course", "a1").MergeRequest

	if mr == nil {
		t.Fatal("MergeRequest = nil, want defaults even when unconfigured")
	}
	if mr.MergeMethod != MergeCommit {
		t.Errorf("MergeMethod = %q, want %q", mr.MergeMethod, MergeCommit)
	}
	if mr.SquashOption != SquashDefaultOff {
		t.Errorf("SquashOption = %q, want %q", mr.SquashOption, SquashDefaultOff)
	}
	if mr.PipelineMustSucceed || mr.SkippedPipelinesAreSuccessful || mr.AllThreadsMustBeResolved || mr.StatusChecksMustSucceed {
		t.Errorf("MergeRequest checks = %#v, want all false by default", mr)
	}
	if mr.Approvals != nil || mr.ApprovalSettings != nil {
		t.Errorf("Approvals = %#v / %#v, want nil", mr.Approvals, mr.ApprovalSettings)
	}
}

func TestMergeRequestMergeMethodAndSquashOption(t *testing.T) {
	registerCourse(t, `
course:
  semi:
    mergeRequest: {mergeMethod: semi_linear}
  ff:
    mergeRequest: {mergeMethod: ff}
  merge:
    mergeRequest: {mergeMethod: merge}
  bogus:
    mergeRequest: {mergeMethod: nonsense}
  never:
    mergeRequest: {squashOption: never}
  always:
    mergeRequest: {squashOption: always}
  defaulton:
    mergeRequest: {squashOption: default_on}
  defaultoff:
    mergeRequest: {squashOption: default_off}
  bogussquash:
    mergeRequest: {squashOption: nonsense}
`)

	for _, tt := range []struct {
		assignment string
		want       MergeMethod
	}{
		{"semi", SemiLinearHistory},
		{"ff", FastForward},
		{"merge", MergeCommit},
		{"bogus", MergeCommit},
	} {
		if got := mustAssignmentConfig(t, "course", tt.assignment).MergeRequest.MergeMethod; got != tt.want {
			t.Errorf("%s: MergeMethod = %q, want %q", tt.assignment, got, tt.want)
		}
	}

	for _, tt := range []struct {
		assignment string
		want       SquashOption
	}{
		{"never", SquashNever},
		{"always", SquashAlways},
		{"defaulton", SquashDefaultOn},
		{"defaultoff", SquashDefaultOff},
		{"bogussquash", SquashDefaultOff},
	} {
		if got := mustAssignmentConfig(t, "course", tt.assignment).MergeRequest.SquashOption; got != tt.want {
			t.Errorf("%s: SquashOption = %q, want %q", tt.assignment, got, tt.want)
		}
	}
}

func TestMergeRequestChecks(t *testing.T) {
	registerCourse(t, `
course:
  a1:
    mergeRequest:
      pipeline: true
      skippedPipelinesAreSuccessful: true
      allThreadsMustBeResolved: true
      statusChecksMustSucceed: true
`)
	mr := mustAssignmentConfig(t, "course", "a1").MergeRequest

	if !mr.PipelineMustSucceed || !mr.SkippedPipelinesAreSuccessful || !mr.AllThreadsMustBeResolved || !mr.StatusChecksMustSucceed {
		t.Errorf("MergeRequest checks = %#v, want all true", mr)
	}
}

func TestMergeRequestApprovals(t *testing.T) {
	registerCourse(t, `
course:
  a1:
    mergeRequest:
      approvals:
        settings:
          preventApprovalByMergeRequestCreator: true
          preventApprovalsByUsersWhoAddCommits: false
          whenCommitAdded: removeAllApprovals
        rules:
          - name: review
            branches: [main, startercode]
            requiredApprovals: 2
            multiMemberGroupsOnly: true
          - name: submission
            branch: startercode
            usernames: [obcode]
            requiredApprovals: 1
`)
	mr := mustAssignmentConfig(t, "course", "a1").MergeRequest

	if len(mr.Approvals) != 2 {
		t.Fatalf("Approvals = %d rules, want 2", len(mr.Approvals))
	}
	if got := mr.Approvals[0]; got.Name != "review" || len(got.Branches) != 2 || got.RequiredApprovals != 2 || !got.MultiMemberGroupsOnly {
		t.Errorf("rule 0 = %#v", got)
	}
	// The deprecated singular `branch` is folded into Branches.
	if got := mr.Approvals[1]; len(got.Branches) != 1 || got.Branches[0] != "startercode" || got.Branch != "" {
		t.Errorf("rule 1 = %#v, want the singular branch folded into Branches", got)
	}

	s := mr.ApprovalSettings
	if s == nil {
		t.Fatal("ApprovalSettings = nil")
	}
	if s.PreventApprovalByMergeRequestCreator == nil || !*s.PreventApprovalByMergeRequestCreator {
		t.Errorf("PreventApprovalByMergeRequestCreator = %v, want true", s.PreventApprovalByMergeRequestCreator)
	}
	if s.PreventApprovalsByUsersWhoAddCommits == nil || *s.PreventApprovalsByUsersWhoAddCommits {
		t.Errorf("PreventApprovalsByUsersWhoAddCommits = %v, want an explicit false", s.PreventApprovalsByUsersWhoAddCommits)
	}
	// Unmentioned settings stay nil so they are never sent to GitLab.
	if s.RequireUserReauthenticationToApprove != nil {
		t.Errorf("RequireUserReauthenticationToApprove = %v, want nil when unconfigured", *s.RequireUserReauthenticationToApprove)
	}
	if s.WhenCommitAdded == nil || *s.WhenCommitAdded != ApprovalRemoveAllApprovals {
		t.Errorf("WhenCommitAdded = %v, want %q", s.WhenCommitAdded, ApprovalRemoveAllApprovals)
	}
}
