// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlc

import (
	"context"
	"time"
)

const activityFor = `-- name: ActivityFor :many

select id, owner, course, assignment, op, params, status, detail, at from activity
 where owner = $1 and course = $2 and assignment = $3
 order by at desc, id desc
 limit $4
`

type ActivityForParams struct {
	Owner      string
	Course     string
	Assignment string
	Lim        *int32
}

// The three reads below all take a nullable limit, because `limit null` means
// "no limit" in PostgreSQL -- exactly the `limit <= 0` case of the findActivity
// helper they replace. The GUI reads pass the cap; the audit dump passes null.
func (q *Queries) ActivityFor(ctx context.Context, arg ActivityForParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, activityFor,
		arg.Owner,
		arg.Course,
		arg.Assignment,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Course,
			&i.Assignment,
			&i.Op,
			&i.Params,
			&i.Status,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allActivityFor = `-- name: AllActivityFor :many
select id, owner, course, assignment, op, params, status, detail, at from activity
 where owner = $1
 order by at desc, id desc
 limit $2
`

type AllActivityForParams struct {
	Owner string
	Lim   *int32
}

func (q *Queries) AllActivityFor(ctx context.Context, arg AllActivityForParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, allActivityFor, arg.Owner, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Course,
			&i.Assignment,
			&i.Op,
			&i.Params,
			&i.Status,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseActivityFor = `-- name: CourseActivityFor :many
select id, owner, course, assignment, op, params, status, detail, at from activity
 where owner = $1 and course = $2
 order by at desc, id desc
 limit $3
`

type CourseActivityForParams struct {
	Owner  string
	Course string
	Lim    *int32
}

func (q *Queries) CourseActivityFor(ctx context.Context, arg CourseActivityForParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, courseActivityFor, arg.Owner, arg.Course, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Course,
			&i.Assignment,
			&i.Op,
			&i.Params,
			&i.Status,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordActivity = `-- name: RecordActivity :exec
insert into activity (owner, course, assignment, op, params, status, detail, at)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordActivityParams struct {
	Owner      string
	Course     string
	Assignment string
	Op         string
	Params     []byte
	Status     string
	Detail     string
	At         time.Time
}

func (q *Queries) RecordActivity(ctx context.Context, arg RecordActivityParams) error {
	_, err := q.db.Exec(ctx, recordActivity,
		arg.Owner,
		arg.Course,
		arg.Assignment,
		arg.Op,
		arg.Params,
		arg.Status,
		arg.Detail,
		arg.At,
	)
	return err
}
