// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlc

import (
	"context"
	"time"
)

const courseOf = `-- name: CourseOf :one
select owner, name, source, format_version, raw_yaml, imported_at, updated_at from courses
 where owner = $1 and name = $2
`

type CourseOfParams struct {
	Owner string
	Name  string
}

func (q *Queries) CourseOf(ctx context.Context, arg CourseOfParams) (Course, error) {
	row := q.db.QueryRow(ctx, courseOf, arg.Owner, arg.Name)
	var i Course
	err := row.Scan(
		&i.Owner,
		&i.Name,
		&i.Source,
		&i.FormatVersion,
		&i.RawYaml,
		&i.ImportedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const coursesOf = `-- name: CoursesOf :many

select owner, name, source, format_version, raw_yaml, imported_at, updated_at from courses
 where owner = $1
 order by name
`

// Every read here takes an owner and filters on it. There is deliberately no
// query that reads a course by name alone: owner isolation is enforced by the
// shape of this file, not by remembering to add a filter at each call site.
func (q *Queries) CoursesOf(ctx context.Context, owner string) ([]Course, error) {
	rows, err := q.db.Query(ctx, coursesOf, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.Owner,
			&i.Name,
			&i.Source,
			&i.FormatVersion,
			&i.RawYaml,
			&i.ImportedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCourse = `-- name: DeleteCourse :execrows
delete from courses
 where owner = $1 and name = $2
`

type DeleteCourseParams struct {
	Owner string
	Name  string
}

// :execrows so the caller can tell "deleted" from "there was nothing to
// delete". Deleting another user's course must report not-found rather than
// pretending it worked.
func (q *Queries) DeleteCourse(ctx context.Context, arg DeleteCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourse, arg.Owner, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveCourse = `-- name: SaveCourse :exec
insert into courses (owner, name, source, raw_yaml, imported_at, updated_at)
values ($1, $2, $3, $4, $5, $6)
on conflict (owner, name) do update
   set source      = excluded.source,
       raw_yaml    = excluded.raw_yaml,
       imported_at = excluded.imported_at,
       updated_at  = excluded.updated_at
`

type SaveCourseParams struct {
	Owner      string
	Name       string
	Source     []byte
	RawYaml    []byte
	ImportedAt time.Time
	UpdatedAt  time.Time
}

// An upsert on the key, replacing the whole row -- what ReplaceOne(upsert) did.
// imported_at is included on purpose: the caller carries it on the struct and a
// replace has to write it back, or editing a course would reset when it was
// imported.
func (q *Queries) SaveCourse(ctx context.Context, arg SaveCourseParams) error {
	_, err := q.db.Exec(ctx, saveCourse,
		arg.Owner,
		arg.Name,
		arg.Source,
		arg.RawYaml,
		arg.ImportedAt,
		arg.UpdatedAt,
	)
	return err
}
