// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"time"
)

const eventsBetween = `-- name: EventsBetween :many
select id, at, type, severity, actor, actor_name, department, course, assignment, op, detail, job_id from events
 where at >= $1 and at < $2
 order by at, id
`

type EventsBetweenParams struct {
	At   time.Time
	At_2 time.Time
}

// [since, until) -- half open on purpose. The upper bound belongs to the NEXT
// digest window; including it would mail the same event twice.
//
// Oldest first, with the id as tiebreaker. Mongo left events sharing a timestamp
// in an arbitrary order; this is a stable total order and a free improvement.
func (q *Queries) EventsBetween(ctx context.Context, arg EventsBetweenParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventsBetween, arg.At, arg.At_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Type,
			&i.Severity,
			&i.Actor,
			&i.ActorName,
			&i.Department,
			&i.Course,
			&i.Assignment,
			&i.Op,
			&i.Detail,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapExpiredEvents = `-- name: ReapExpiredEvents :execrows
delete from events
 where at < $1::timestamptz
`

// The replacement for Mongo's TTL index on at: the monitoring trail is a rolling
// window, not a permanent archive.
func (q *Queries) ReapExpiredEvents(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredEvents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recentEvents = `-- name: RecentEvents :many
select id, at, type, severity, actor, actor_name, department, course, assignment, op, detail, job_id from events
 where at >= $1
 order by at desc, id desc
 limit $2
`

type RecentEventsParams struct {
	At  time.Time
	Lim *int32
}

// The admin page's live feed. A null limit means unlimited, as with activity.
func (q *Queries) RecentEvents(ctx context.Context, arg RecentEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, recentEvents, arg.At, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Type,
			&i.Severity,
			&i.Actor,
			&i.ActorName,
			&i.Department,
			&i.Course,
			&i.Assignment,
			&i.Op,
			&i.Detail,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :exec
insert into events (at, type, severity, actor, actor_name, department, course, assignment, op, detail, job_id)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type RecordEventParams struct {
	At         time.Time
	Type       string
	Severity   string
	Actor      string
	ActorName  string
	Department string
	Course     string
	Assignment string
	Op         string
	Detail     string
	JobID      string
}

func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) error {
	_, err := q.db.Exec(ctx, recordEvent,
		arg.At,
		arg.Type,
		arg.Severity,
		arg.Actor,
		arg.ActorName,
		arg.Department,
		arg.Course,
		arg.Assignment,
		arg.Op,
		arg.Detail,
		arg.JobID,
	)
	return err
}
