// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"time"
)

const cancelJob = `-- name: CancelJob :one
update scheduled_jobs
   set status = 'cancelled', finished_at = $3::timestamptz
 where id = $1 and owner = $2 and status = 'pending'
returning id, owner, op, course, assignment, only_for, params, run_at, config_hash, status, grace_minutes, created_at, started_at, finished_at, log, err, notified, worker_id
`

type CancelJobParams struct {
	ID         string
	Owner      string
	FinishedAt time.Time
}

// Only one's own, only while still pending. A job already running is too late
// and another owner's job is invisible: both return no row, and the caller turns
// that into the same error. That sameness is deliberate -- "not found" must not
// become an oracle for whether someone else has a job with that id.
func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, cancelJob, arg.ID, arg.Owner, arg.FinishedAt)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Op,
		&i.Course,
		&i.Assignment,
		&i.OnlyFor,
		&i.Params,
		&i.RunAt,
		&i.ConfigHash,
		&i.Status,
		&i.GraceMinutes,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Log,
		&i.Err,
		&i.Notified,
		&i.WorkerID,
	)
	return i, err
}

const claimDueJob = `-- name: ClaimDueJob :one
update scheduled_jobs
   set status = 'running', started_at = $1::timestamptz, worker_id = $2
 where id = (
       select id from scheduled_jobs
        where status = 'pending' and run_at <= $1::timestamptz
        order by run_at
          for update skip locked
        limit 1)
returning id, owner, op, course, assignment, only_for, params, run_at, config_hash, status, grace_minutes, created_at, started_at, finished_at, log, err, notified, worker_id
`

type ClaimDueJobParams struct {
	Now      time.Time
	WorkerID string
}

// The atomic claim. This single statement is what replaces a distributed lock:
// exactly one runner ever owns a given job.
//
// FOR UPDATE SKIP LOCKED is strictly stronger than the FindOneAndUpdate it
// replaces -- several runners do not queue behind each other, they take
// different jobs.
//
// Deliberately NOT wrapped in an explicit transaction. The row lock ends with
// the statement, and the flip to 'running' IS the lock. Holding a transaction
// open across the job's execution would mean minutes with a locked row and a
// pool connection tied up, which is the obvious-looking mistake here.
func (q *Queries) ClaimDueJob(ctx context.Context, arg ClaimDueJobParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, claimDueJob, arg.Now, arg.WorkerID)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Op,
		&i.Course,
		&i.Assignment,
		&i.OnlyFor,
		&i.Params,
		&i.RunAt,
		&i.ConfigHash,
		&i.Status,
		&i.GraceMinutes,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Log,
		&i.Err,
		&i.Notified,
		&i.WorkerID,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :exec
update scheduled_jobs
   set status = $2, finished_at = $5::timestamptz, log = $3, err = $4
 where id = $1
`

type FinishJobParams struct {
	ID         string
	Status     string
	Log        string
	Err        string
	FinishedAt time.Time
}

// Matching nothing is success, as before: the runner logs an error here, and a
// job the retention sweep has already removed should not produce noise.
func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob,
		arg.ID,
		arg.Status,
		arg.Log,
		arg.Err,
		arg.FinishedAt,
	)
	return err
}

const jobOf = `-- name: JobOf :one
select id, owner, op, course, assignment, only_for, params, run_at, config_hash, status, grace_minutes, created_at, started_at, finished_at, log, err, notified, worker_id from scheduled_jobs
 where id = $1 and owner = $2
`

type JobOfParams struct {
	ID    string
	Owner string
}

func (q *Queries) JobOf(ctx context.Context, arg JobOfParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, jobOf, arg.ID, arg.Owner)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Op,
		&i.Course,
		&i.Assignment,
		&i.OnlyFor,
		&i.Params,
		&i.RunAt,
		&i.ConfigHash,
		&i.Status,
		&i.GraceMinutes,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Log,
		&i.Err,
		&i.Notified,
		&i.WorkerID,
	)
	return i, err
}

const jobsOf = `-- name: JobsOf :many
select id, owner, op, course, assignment, only_for, params, run_at, config_hash, status, grace_minutes, created_at, started_at, finished_at, log, err, notified, worker_id from scheduled_jobs
 where owner = $1
   and (coalesce(cardinality($2::text[]), 0) = 0 or status = any($2::text[]))
 order by run_at desc, id desc
`

type JobsOfParams struct {
	Owner    string
	Statuses []string
}

// The status list is optional: empty or null means no filter, which is what the
// GUI's unfiltered view passes. Spelled with cardinality rather than a second
// query so there is one ordering to keep correct.
func (q *Queries) JobsOf(ctx context.Context, arg JobsOfParams) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, jobsOf, arg.Owner, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Op,
			&i.Course,
			&i.Assignment,
			&i.OnlyFor,
			&i.Params,
			&i.RunAt,
			&i.ConfigHash,
			&i.Status,
			&i.GraceMinutes,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Log,
			&i.Err,
			&i.Notified,
			&i.WorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotified = `-- name: MarkNotified :exec
update scheduled_jobs
   set notified = true
 where id = $1
`

func (q *Queries) MarkNotified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markNotified, id)
	return err
}

const reapExpiredJobs = `-- name: ReapExpiredJobs :execrows
delete from scheduled_jobs
 where finished_at < $1::timestamptz
`

// The replacement for Mongo's TTL index on finished_at. `finished_at is null`
// falls out of the comparison on its own, so pending and running jobs are never
// reaped -- exactly what the partial TTL index did.
func (q *Queries) ReapExpiredJobs(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredJobs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveJob = `-- name: SaveJob :exec
insert into scheduled_jobs (
    id, owner, op, course, assignment, only_for, params,
    run_at, config_hash, status, grace_minutes, created_at,
    started_at, finished_at, log, err, notified, worker_id
) values (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18
)
`

type SaveJobParams struct {
	ID           string
	Owner        string
	Op           string
	Course       string
	Assignment   string
	OnlyFor      []string
	Params       []byte
	RunAt        time.Time
	ConfigHash   string
	Status       string
	GraceMinutes int
	CreatedAt    time.Time
	StartedAt    *time.Time
	FinishedAt   *time.Time
	Log          string
	Err          string
	Notified     bool
	WorkerID     string
}

func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) error {
	_, err := q.db.Exec(ctx, saveJob,
		arg.ID,
		arg.Owner,
		arg.Op,
		arg.Course,
		arg.Assignment,
		arg.OnlyFor,
		arg.Params,
		arg.RunAt,
		arg.ConfigHash,
		arg.Status,
		arg.GraceMinutes,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Log,
		arg.Err,
		arg.Notified,
		arg.WorkerID,
	)
	return err
}

const unnotifiedTerminalJobs = `-- name: UnnotifiedTerminalJobs :many
select id, owner, op, course, assignment, only_for, params, run_at, config_hash, status, grace_minutes, created_at, started_at, finished_at, log, err, notified, worker_id from scheduled_jobs
 where notified = false
   and status in ('done', 'failed', 'expired')
 order by finished_at, id
`

// The runner's notify sweep, across all owners: one mail per finished job.
// Cancelled is excluded -- the user did that on purpose and there is no mail for
// it. This is what makes "mail on every terminal state" survive a crash between
// finishing a job and mailing it.
func (q *Queries) UnnotifiedTerminalJobs(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, unnotifiedTerminalJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Op,
			&i.Course,
			&i.Assignment,
			&i.OnlyFor,
			&i.Params,
			&i.RunAt,
			&i.ConfigHash,
			&i.Status,
			&i.GraceMinutes,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Log,
			&i.Err,
			&i.Notified,
			&i.WorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
