// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Activity struct {
	ID         int64
	Owner      string
	Course     string
	Assignment string
	Op         string
	Params     []byte
	Status     string
	Detail     string
	At         time.Time
}

type Course struct {
	Owner         string
	Name          string
	Source        []byte
	FormatVersion int
	RawYaml       []byte
	ImportedAt    time.Time
	UpdatedAt     time.Time
}

type Event struct {
	ID         int64
	At         time.Time
	Type       string
	Severity   string
	Actor      string
	ActorName  string
	Department string
	Course     string
	Assignment string
	Op         string
	Detail     string
	JobID      string
}

type ScheduledJob struct {
	ID           string
	Owner        string
	Op           string
	Course       string
	Assignment   string
	OnlyFor      []string
	Params       []byte
	RunAt        time.Time
	ConfigHash   string
	Status       string
	GraceMinutes int
	CreatedAt    time.Time
	StartedAt    *time.Time
	FinishedAt   *time.Time
	Log          string
	Err          string
	Notified     bool
	WorkerID     string
}

type SystemState struct {
	ID            string
	SummarySentAt *time.Time
}

type User struct {
	Email       string
	Name        string
	Department  string
	Status      string
	Reason      string
	RequestedAt time.Time
	DecidedAt   *time.Time
	DecidedBy   string
}

type UserSecret struct {
	Owner            string
	GitlabKeyVersion *int
	GitlabNonce      []byte
	GitlabCiphertext []byte
	GitlabUpdatedAt  *time.Time
}
