// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	// The three reads below all take a nullable limit, because `limit null` means
	// "no limit" in PostgreSQL -- exactly the `limit <= 0` case of the findActivity
	// helper they replace. The GUI reads pass the cap; the audit dump passes null.
	ActivityFor(ctx context.Context, arg ActivityForParams) ([]Activity, error)
	AllActivityFor(ctx context.Context, arg AllActivityForParams) ([]Activity, error)
	// Only one's own, only while still pending. A job already running is too late
	// and another owner's job is invisible: both return no row, and the caller turns
	// that into the same error. That sameness is deliberate -- "not found" must not
	// become an oracle for whether someone else has a job with that id.
	CancelJob(ctx context.Context, arg CancelJobParams) (ScheduledJob, error)
	// The atomic claim. This single statement is what replaces a distributed lock:
	// exactly one runner ever owns a given job.
	//
	// FOR UPDATE SKIP LOCKED is strictly stronger than the FindOneAndUpdate it
	// replaces -- several runners do not queue behind each other, they take
	// different jobs.
	//
	// Deliberately NOT wrapped in an explicit transaction. The row lock ends with
	// the statement, and the flip to 'running' IS the lock. Holding a transaction
	// open across the job's execution would mean minutes with a locked row and a
	// pool connection tied up, which is the obvious-looking mistake here.
	ClaimDueJob(ctx context.Context, arg ClaimDueJobParams) (ScheduledJob, error)
	CourseActivityFor(ctx context.Context, arg CourseActivityForParams) ([]Activity, error)
	CourseOf(ctx context.Context, arg CourseOfParams) (Course, error)
	// Every read here takes an owner and filters on it. There is deliberately no
	// query that reads a course by name alone: owner isolation is enforced by the
	// shape of this file, not by remembering to add a filter at each call site.
	CoursesOf(ctx context.Context, owner string) ([]Course, error)
	// :execrows so the caller can tell "deleted" from "there was nothing to
	// delete". Deleting another user's course must report not-found rather than
	// pretending it worked.
	DeleteCourse(ctx context.Context, arg DeleteCourseParams) (int64, error)
	// An update to null, not a delete of the row: the row is the anchor for the
	// other per-user secrets this table is meant to grow, and removing a GitLab
	// token must not take them with it. Exactly the $unset semantics.
	//
	// A row that does not exist matches nothing and reports success, as before: the
	// caller's intent is "make sure there is none".
	DeleteUserGitLabToken(ctx context.Context, owner string) error
	// [since, until) -- half open on purpose. The upper bound belongs to the NEXT
	// digest window; including it would mail the same event twice.
	//
	// Oldest first, with the id as tiebreaker. Mongo left events sharing a timestamp
	// in an arbitrary order; this is a stable total order and a free improvement.
	EventsBetween(ctx context.Context, arg EventsBetweenParams) ([]Event, error)
	// Matching nothing is success, as before: the runner logs an error here, and a
	// job the retention sweep has already removed should not produce noise.
	FinishJob(ctx context.Context, arg FinishJobParams) error
	GetUserSecret(ctx context.Context, owner string) (UserSecret, error)
	JobOf(ctx context.Context, arg JobOfParams) (ScheduledJob, error)
	// The status list is optional: empty or null means no filter, which is what the
	// GUI's unfiltered view passes. Spelled with cardinality rather than a second
	// query so there is one ordering to keep correct.
	JobsOf(ctx context.Context, arg JobsOfParams) ([]ScheduledJob, error)
	MarkNotified(ctx context.Context, id string) error
	// The replacement for Mongo's TTL index on at: the monitoring trail is a rolling
	// window, not a permanent archive.
	ReapExpiredEvents(ctx context.Context, before time.Time) (int64, error)
	// The replacement for Mongo's TTL index on finished_at. `finished_at is null`
	// falls out of the comparison on its own, so pending and running jobs are never
	// reaped -- exactly what the partial TTL index did.
	ReapExpiredJobs(ctx context.Context, before time.Time) (int64, error)
	// The admin page's live feed. A null limit means unlimited, as with activity.
	RecentEvents(ctx context.Context, arg RecentEventsParams) ([]Event, error)
	RecordActivity(ctx context.Context, arg RecordActivityParams) error
	RecordEvent(ctx context.Context, arg RecordEventParams) error
	// An upsert on the key, replacing the whole row -- what ReplaceOne(upsert) did.
	// imported_at is included on purpose: the caller carries it on the struct and a
	// replace has to write it back, or editing a course would reset when it was
	// imported.
	SaveCourse(ctx context.Context, arg SaveCourseParams) error
	SaveJob(ctx context.Context, arg SaveJobParams) error
	// The column list is what makes this touch only the gitlab fields: other
	// secrets on the row survive. In Mongo that was a $set of three named keys and
	// depended on remembering to name them.
	SaveUserGitLabToken(ctx context.Context, arg SaveUserGitLabTokenParams) error
	// Self-healing: the row is seeded by the migration, but an upsert means a
	// vanished row does not turn the nightly digest into a permanent failure.
	SetSummarySentAt(ctx context.Context, summarySentAt *time.Time) error
	SystemState(ctx context.Context) (SystemState, error)
	// The runner's notify sweep, across all owners: one mail per finished job.
	// Cancelled is excluded -- the user did that on purpose and there is no mail for
	// it. This is what makes "mail on every terminal state" survive a crash between
	// finishing a job and mailing it.
	UnnotifiedTerminalJobs(ctx context.Context) ([]ScheduledJob, error)
}

var _ Querier = (*Queries)(nil)
