// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package sqlc

import (
	"context"
	"time"
)

const setSummarySentAt = `-- name: SetSummarySentAt :exec
insert into system_state (id, summary_sent_at)
values ('state', $1)
on conflict (id) do update
   set summary_sent_at = excluded.summary_sent_at
`

// Self-healing: the row is seeded by the migration, but an upsert means a
// vanished row does not turn the nightly digest into a permanent failure.
func (q *Queries) SetSummarySentAt(ctx context.Context, summarySentAt *time.Time) error {
	_, err := q.db.Exec(ctx, setSummarySentAt, summarySentAt)
	return err
}

const systemState = `-- name: SystemState :one
select id, summary_sent_at from system_state
 where id = 'state'
`

func (q *Queries) SystemState(ctx context.Context) (SystemState, error) {
	row := q.db.QueryRow(ctx, systemState)
	var i SystemState
	err := row.Scan(&i.ID, &i.SummarySentAt)
	return i, err
}
