// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_secrets.sql

package sqlc

import (
	"context"
	"time"
)

const deleteUserGitLabToken = `-- name: DeleteUserGitLabToken :exec
update user_secrets
   set gitlab_key_version = null,
       gitlab_nonce       = null,
       gitlab_ciphertext  = null,
       gitlab_updated_at  = null
 where owner = $1
`

// An update to null, not a delete of the row: the row is the anchor for the
// other per-user secrets this table is meant to grow, and removing a GitLab
// token must not take them with it. Exactly the $unset semantics.
//
// A row that does not exist matches nothing and reports success, as before: the
// caller's intent is "make sure there is none".
func (q *Queries) DeleteUserGitLabToken(ctx context.Context, owner string) error {
	_, err := q.db.Exec(ctx, deleteUserGitLabToken, owner)
	return err
}

const getUserSecret = `-- name: GetUserSecret :one
select owner, gitlab_key_version, gitlab_nonce, gitlab_ciphertext, gitlab_updated_at from user_secrets
 where owner = $1
`

func (q *Queries) GetUserSecret(ctx context.Context, owner string) (UserSecret, error) {
	row := q.db.QueryRow(ctx, getUserSecret, owner)
	var i UserSecret
	err := row.Scan(
		&i.Owner,
		&i.GitlabKeyVersion,
		&i.GitlabNonce,
		&i.GitlabCiphertext,
		&i.GitlabUpdatedAt,
	)
	return i, err
}

const saveUserGitLabToken = `-- name: SaveUserGitLabToken :exec
insert into user_secrets (owner, gitlab_key_version, gitlab_nonce, gitlab_ciphertext, gitlab_updated_at)
values ($1, $2, $3, $4, $5)
on conflict (owner) do update
   set gitlab_key_version = excluded.gitlab_key_version,
       gitlab_nonce       = excluded.gitlab_nonce,
       gitlab_ciphertext  = excluded.gitlab_ciphertext,
       gitlab_updated_at  = excluded.gitlab_updated_at
`

type SaveUserGitLabTokenParams struct {
	Owner            string
	GitlabKeyVersion *int
	GitlabNonce      []byte
	GitlabCiphertext []byte
	GitlabUpdatedAt  *time.Time
}

// The column list is what makes this touch only the gitlab fields: other
// secrets on the row survive. In Mongo that was a $set of three named keys and
// depended on remembering to name them.
func (q *Queries) SaveUserGitLabToken(ctx context.Context, arg SaveUserGitLabTokenParams) error {
	_, err := q.db.Exec(ctx, saveUserGitLabToken,
		arg.Owner,
		arg.GitlabKeyVersion,
		arg.GitlabNonce,
		arg.GitlabCiphertext,
		arg.GitlabUpdatedAt,
	)
	return err
}
