// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const deleteUser = `-- name: DeleteUser :execrows
delete from users
 where email = $1
`

func (q *Queries) DeleteUser(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
select email, name, department, status, reason, requested_at, decided_at, decided_by from users
 where email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Name,
		&i.Department,
		&i.Status,
		&i.Reason,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const insertAccessRequest = `-- name: InsertAccessRequest :one
insert into users (email, name, department, status, reason, requested_at)
values ($1, $2, $3, 'pending', $4, $5)
on conflict (email) do nothing
returning email, name, department, status, reason, requested_at, decided_at, decided_by
`

type InsertAccessRequestParams struct {
	Email       string
	Name        string
	Department  string
	Reason      string
	RequestedAt time.Time
}

// `do nothing` on a conflict, so a double click or a second tab cannot turn one
// request into two admin mails: only the insert that actually created the row
// gets a row back, the other gets pgx.ErrNoRows.
func (q *Queries) InsertAccessRequest(ctx context.Context, arg InsertAccessRequestParams) (User, error) {
	row := q.db.QueryRow(ctx, insertAccessRequest,
		arg.Email,
		arg.Name,
		arg.Department,
		arg.Reason,
		arg.RequestedAt,
	)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Name,
		&i.Department,
		&i.Status,
		&i.Reason,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select email, name, department, status, reason, requested_at, decided_at, decided_by from users
 order by status = 'pending' desc, requested_at desc
`

// Open requests first (they are what an admin comes here for), then everyone
// else; newest request first within each group.
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Email,
			&i.Name,
			&i.Department,
			&i.Status,
			&i.Reason,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :one
update users
   set status     = $2,
       decided_at = $3,
       decided_by = $4
 where email = $1
returning email, name, department, status, reason, requested_at, decided_at, decided_by
`

type SetUserStatusParams struct {
	Email     string
	Status    string
	DecidedAt *time.Time
	DecidedBy string
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus,
		arg.Email,
		arg.Status,
		arg.DecidedAt,
		arg.DecidedBy,
	)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Name,
		&i.Department,
		&i.Status,
		&i.Reason,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}
