name: ci
on:
    push:
        branches:
            - "**"

permissions:
    contents: write

jobs:
    golangci:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v2
              with:
                  version: latest
                  args: --timeout=10m
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.22
              uses: actions/setup-go@v1
              with:
                  go-version: 1.22
              id: go

            - name: Check out code into the Go module directory
              uses: actions/checkout@v1

            - name: Get dependencies
              run: |
                  go get -v -t -d ./...
                  if [ -f Gopkg.toml ]; then
                      curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                      dep ensure
                  fi

            - name: Test
              run: |
                  go test -v ./...
    release:
        runs-on: ubuntu-latest
        needs:
            - golangci
            - test
        steps:
            - uses: actions/checkout@master
              with:
                  persist-credentials: false
            - uses: go-semantic-release/action@v1
              with:
                  changelog-generator-opt: "emojis=true"
                  allow-initial-development-versions: true
                  hooks: goreleaser
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
